// expenseTrack_ui/src/app/libs/feature/expenses/expenses-page.component.ts
import { Component, DestroyRef, OnInit, inject } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, Validators } from '@angular/forms';
import { finalize, forkJoin, timeout } from 'rxjs';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from '../../data-access/auth/auth.service';
import { CategoriesService } from '../../data-access/categories/categories.service';
import { DashboardService } from '../../data-access/dashboard/dashboard.service';
import { ExpensesService } from '../../data-access/expenses/expenses.service';
import { ReportsService } from '../../data-access/reports/reports.service';
import { Category, EntryType, Expense, User } from '../../../../models';

interface CurrencyOption {
  code: string;
  label: string;
}

@Component({
  selector: 'expenses-page',
  standalone: false,
  templateUrl: './expenses-page.component.html',
  styleUrl: './expenses-page.component.scss',
})
export class ExpensesPageComponent implements OnInit {
  private expensesService = inject(ExpensesService);
  private categoriesService = inject(CategoriesService);
  private dashboardService = inject(DashboardService);
  private auth = inject(AuthService);
  private fb = inject(FormBuilder);
  private reportsService = inject(ReportsService);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  private destroyRef = inject(DestroyRef);

  user: User | null = null;
  expenses: Expense[] = [];
  categories: Category[] = [];
  loading = true;
  dialogOpen = false;
  saving = false;
  editingExpense: Expense | null = null;
  searchTerm = '';
  filterCategory = 'all';
  activeEntryType: EntryType = 'expense';
  error = '';
  success = '';

  readonly currencies: CurrencyOption[] = [
    { code: 'USD', label: 'USD ($)' },
    { code: 'EUR', label: 'EUR (EUR)' },
    { code: 'GBP', label: 'GBP (GBP)' },
    { code: 'INR', label: 'INR (INR)' },
    { code: 'JPY', label: 'JPY (JPY)' },
    { code: 'CAD', label: 'CAD (CAD)' },
    { code: 'AUD', label: 'AUD (AUD)' },
  ];

  form = this.fb.nonNullable.group({
    amount: ['', Validators.required],
    currency: ['USD', Validators.required],
    description: ['', Validators.required],
    entry_type: ['expense' as EntryType, Validators.required],
    category_id: ['', Validators.required],
    subcategory_id: [''],
    date: [this.todayDate(), Validators.required],
  });

  ngOnInit(): void {
    this.watchAddExpenseIntent();

    this.user = this.auth.user;
    if (!this.user && this.auth.token) {
      this.auth.me().subscribe({
        next: (user) => {
          this.user = user;
          this.form.patchValue({ currency: user.preferred_currency || 'USD' });
        },
      });
    } else {
      this.form.patchValue({ currency: this.user?.preferred_currency || 'USD' });
    }
    this.fetchData();
  }

  get selectedCategory(): Category | undefined {
    const entryType = this.form.controls.entry_type.value;
    return this.getCategory(this.form.controls.category_id.value, entryType);
  }

  get formCategories(): Category[] {
    const entryType = this.form.controls.entry_type.value;
    return this.categories.filter((category) => category.entry_type === entryType);
  }

  get filterCategories(): Category[] {
    return this.categories.filter((category) => category.entry_type === this.activeEntryType);
  }

  get filteredExpenses(): Expense[] {
    return this.expenses.filter((expense) => {
      const matchesSearch = expense.description
        .toLowerCase()
        .includes(this.searchTerm.toLowerCase());
      const matchesCategory =
        this.filterCategory === 'all' || expense.category_id === this.filterCategory;
      const entryType = expense.entry_type || 'expense';
      const matchesEntryType = entryType === this.activeEntryType;
      return matchesSearch && matchesCategory && matchesEntryType;
    });
  }

  openAddDialog(entryType: EntryType = 'expense'): void {
    this.setActiveEntryType(entryType);
    this.editingExpense = null;
    this.success = '';
    this.error = '';
    this.form.reset({
      amount: '',
      currency: this.user?.preferred_currency || 'USD',
      description: '',
      entry_type: entryType,
      category_id: '',
      subcategory_id: '',
      date: this.todayDate(),
    });
    this.dialogOpen = true;
  }

  openEditDialog(expense: Expense): void {
    this.setActiveEntryType(expense.entry_type || 'expense');
    this.editingExpense = expense;
    this.success = '';
    this.error = '';
    this.form.reset({
      amount: String(expense.amount),
      currency: expense.currency,
      description: expense.description,
      entry_type: expense.entry_type || 'expense',
      category_id: expense.category_id,
      subcategory_id: expense.subcategory_id || '',
      date: this.toInputDate(expense.date),
    });
    this.dialogOpen = true;
  }

  closeDialog(): void {
    this.dialogOpen = false;
    this.editingExpense = null;
    this.saving = false;
    this.form.markAsPristine();
  }

  onCategoryChange(): void {
    this.form.patchValue({ subcategory_id: '' });
  }

  onEntryTypeChange(): void {
    this.form.patchValue({
      category_id: '',
      subcategory_id: '',
    });
  }

  onFilterCategorySelected(categoryId: string): void {
    this.filterCategory = categoryId || 'all';
  }

  setActiveEntryType(entryType: EntryType): void {
    if (this.activeEntryType === entryType) {
      return;
    }

    this.activeEntryType = entryType;
    this.filterCategory = 'all';
  }

  saveExpense(): void {
    if (this.form.invalid || this.saving) {
      this.form.markAllAsTouched();
      return;
    }

    this.saving = true;
    this.error = '';
    this.success = '';

    const raw = this.form.getRawValue();
    const payload = {
      amount: Number(raw.amount),
      currency: raw.currency,
      description: raw.description,
      entry_type: raw.entry_type,
      category_id: raw.category_id,
      subcategory_id: raw.subcategory_id || null,
      date: new Date(raw.date).toISOString(),
    };

    const request$ = this.editingExpense
      ? this.expensesService.update(this.editingExpense.expense_id, payload)
      : this.expensesService.create(payload);

    const saveWatchdog = setTimeout(() => {
      if (!this.saving) {
        return;
      }

      this.error = 'Save response is delayed. Syncing latest expenses now.';
      this.dialogOpen = false;
      this.editingExpense = null;
      this.dashboardService.invalidateCache();
      this.reportsService.invalidateSummaryCache();
      this.fetchData(true);
    }, 10000);

    request$
      .pipe(
        timeout(15000),
        finalize(() => {
          clearTimeout(saveWatchdog);
          this.saving = false;
        })
      )
      .subscribe({
        next: () => {
          this.success = this.editingExpense ? 'Expense updated.' : 'Expense added.';
          this.dialogOpen = false;
          this.editingExpense = null;
          this.dashboardService.invalidateCache();
          this.reportsService.invalidateSummaryCache();
          this.fetchData(true);
        },
        error: (error) => {
          if (error?.name === 'TimeoutError') {
            this.error = 'Save request timed out. Syncing latest expenses now.';
            this.dialogOpen = false;
            this.editingExpense = null;
            this.dashboardService.invalidateCache();
            this.reportsService.invalidateSummaryCache();
            this.fetchData(true);
            return;
          }

          this.error = 'Failed to save expense.';
        },
      });
  }

  deleteExpense(expense: Expense): void {
    const confirmed = window.confirm('Are you sure you want to delete this expense?');
    if (!confirmed) {
      return;
    }

    this.error = '';
    this.success = '';

    this.expensesService.delete(expense.expense_id).subscribe({
      next: () => {
        this.success = 'Expense deleted.';
        this.dashboardService.invalidateCache();
        this.reportsService.invalidateSummaryCache();
        this.fetchData(true);
      },
      error: () => {
        this.error = 'Failed to delete expense.';
      },
    });
  }

  getCategory(categoryId: string, entryType?: EntryType): Category | undefined {
    return this.categories.find((category) => {
      if (category.category_id !== categoryId) {
        return false;
      }
      if (!entryType) {
        return true;
      }
      return category.entry_type === entryType;
    });
  }

  getSubcategory(categoryId: string, subcategoryId?: string | null, entryType?: EntryType): string {
    if (!subcategoryId) {
      return '';
    }
    const category = this.getCategory(categoryId, entryType);
    return (
      category?.subcategories?.find((subcategory) => subcategory.subcategory_id === subcategoryId)
        ?.name || ''
    );
  }

  formatCurrency(amount: number, currency?: string | null): string {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: currency || 'USD',
    }).format(amount);
  }

  formatSignedAmount(expense: Expense): string {
    const entryType = expense.entry_type || 'expense';
    const amount = this.formatCurrency(expense.amount, expense.currency);
    return entryType === 'income' ? `+${amount}` : `-${amount}`;
  }

  formatDate(date: string): string {
    const parsed = new Date(date);
    if (Number.isNaN(parsed.getTime())) {
      return date;
    }
    return parsed.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    });
  }

  private fetchData(forceRefresh = false): void {
    this.loading = true;
    this.error = '';

    forkJoin({
      expenses: this.expensesService.list(forceRefresh),
      categories: this.categoriesService.list(forceRefresh),
    }).subscribe({
      next: ({ expenses, categories }) => {
        this.expenses = expenses;
        this.categories = categories;
        this.loading = false;
      },
      error: () => {
        this.error = 'Failed to load expenses.';
        this.loading = false;
      },
    });
  }

  private watchAddExpenseIntent(): void {
    this.route.queryParamMap
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe((params) => {
        if (params.get('action') !== 'add') {
          if (params.get('action') === 'add-income') {
            this.openAddDialog('income');
            this.router.navigate([], {
              relativeTo: this.route,
              queryParams: { action: null },
              queryParamsHandling: 'merge',
              replaceUrl: true,
            });
          } else if (params.get('action') === 'add-expense') {
            this.openAddDialog('expense');
            this.router.navigate([], {
              relativeTo: this.route,
              queryParams: { action: null },
              queryParamsHandling: 'merge',
              replaceUrl: true,
            });
          }
          return;
        }

        this.openAddDialog('expense');
        this.router.navigate([], {
          relativeTo: this.route,
          queryParams: { action: null },
          queryParamsHandling: 'merge',
          replaceUrl: true,
        });
      });
  }

  private todayDate(): string {
    return this.toInputDate(new Date().toISOString());
  }

  private toInputDate(value: string): string {
    const parsed = new Date(value);
    if (Number.isNaN(parsed.getTime())) {
      return value.slice(0, 10);
    }
    return parsed.toISOString().slice(0, 10);
  }
}

<div class="page" data-testid="expenses-page">
  <div class="page-header">
    <div>
      <h1>Transactions</h1>
      <p>Track and manage your expenses and income</p>
    </div>
    <div class="header-actions">
      <button type="button" class="btn-secondary" (click)="openAddDialog('income')" data-testid="add-income-dialog-btn">
        Add Income
      </button>
      <button type="button" class="btn-primary" (click)="openAddDialog('expense')" data-testid="add-expense-dialog-btn">
        Add Expense
      </button>
    </div>
  </div>

  <p class="error" *ngIf="error">{{ error }}</p>
  <p class="success" *ngIf="success">{{ success }}</p>

  <nav class="entry-toggle" aria-label="Transaction type switch">
    <button
      type="button"
      [class.active]="activeEntryType === 'expense'"
      (click)="setActiveEntryType('expense')"
      data-testid="transactions-expense-toggle"
    >
      Expenses
    </button>
    <button
      type="button"
      [class.active]="activeEntryType === 'income'"
      (click)="setActiveEntryType('income')"
      data-testid="transactions-income-toggle"
    >
      Income
    </button>
  </nav>

  <section class="filters">
    <div class="search-field">
      <input
        type="search"
        placeholder="Search transactions..."
        [(ngModel)]="searchTerm"
        data-testid="expense-search-input"
      />
      <button
        *ngIf="searchTerm"
        type="button"
        class="clear-chip"
        (click)="searchTerm = ''"
        aria-label="Clear transaction search"
      >
        Clear
      </button>
    </div>
    <div class="category-filter-wrap">
      <label class="sr-only" for="filter-category">Category</label>
      <select
        id="filter-category"
        class="category-filter-control"
        [(ngModel)]="filterCategory"
        (ngModelChange)="onFilterCategorySelected($event)"
        data-testid="expense-filter-category-search-input"
      >
        <option value="all">All Categories</option>
        <option *ngFor="let category of filterCategories" [value]="category.category_id">
          {{ category.name }}
        </option>
      </select>
    </div>
  </section>

  <section class="list-card">
    <div class="list-skeleton" *ngIf="loading" aria-label="Loading expenses">
      <article class="skeleton-expense-item" *ngFor="let _ of [1, 2, 3, 4, 5]">
        <div class="skeleton-left">
          <span class="skeleton skeleton-avatar"></span>
          <div class="skeleton-copy">
            <span class="skeleton skeleton-line skeleton-line-md"></span>
            <span class="skeleton skeleton-line skeleton-line-sm"></span>
          </div>
        </div>
        <div class="skeleton-right">
          <span class="skeleton skeleton-line skeleton-amount"></span>
          <span class="skeleton skeleton-line skeleton-date"></span>
        </div>
      </article>
    </div>

    <div class="empty" *ngIf="!loading && !filteredExpenses.length">
      No transactions found. Add your first entry.
    </div>

    <ng-container *ngIf="!loading">
      <article
        class="expense-item"
        *ngFor="let expense of filteredExpenses"
        [attr.data-testid]="'expense-item-' + expense.expense_id"
      >
        <div class="left">
          <div class="avatar" [style.backgroundColor]="getCategory(expense.category_id, expense.entry_type || 'expense')?.color || '#064E3B'">
            {{ getCategory(expense.category_id, expense.entry_type || 'expense')?.name?.charAt(0) || (expense.entry_type === 'income' ? 'I' : 'E') }}
          </div>
          <div class="copy">
            <p class="description">{{ expense.description }}</p>
            <p class="meta">
              <span class="type-badge" [class.income]="expense.entry_type === 'income'" [class.expense]="expense.entry_type !== 'income'">
                {{ expense.entry_type === 'income' ? 'Income' : 'Expense' }}
              </span>
              {{ getCategory(expense.category_id, expense.entry_type || 'expense')?.name || 'Category' }}
              <span *ngIf="getSubcategory(expense.category_id, expense.subcategory_id, expense.entry_type || 'expense')">
                > {{ getSubcategory(expense.category_id, expense.subcategory_id, expense.entry_type || 'expense') }}
              </span>
            </p>
          </div>
        </div>

        <div class="right">
          <div class="amount-wrap">
            <p class="amount" [class.income]="expense.entry_type === 'income'" [class.expense]="expense.entry_type !== 'income'">
              {{ formatSignedAmount(expense) }}
            </p>
            <p class="date">{{ formatDate(expense.date) }}</p>
          </div>
          <div class="actions">
            <button type="button" class="icon-btn" (click)="openEditDialog(expense)" [attr.data-testid]="'edit-expense-' + expense.expense_id">
              Edit
            </button>
            <button
              type="button"
              class="icon-btn danger"
              (click)="deleteExpense(expense)"
              [attr.data-testid]="'delete-expense-' + expense.expense_id"
            >
              Delete
            </button>
          </div>
        </div>
      </article>
    </ng-container>
  </section>
</div>

<div class="modal-backdrop" *ngIf="dialogOpen">
  <div class="modal">
    <div class="modal-header">
      <h2>{{ editingExpense ? 'Edit Transaction' : (form.controls.entry_type.value === 'income' ? 'Add New Income' : 'Add New Expense') }}</h2>
      <button type="button" class="close-btn" (click)="closeDialog()">X</button>
    </div>

    <form [formGroup]="form" (ngSubmit)="saveExpense()">
      <div class="field-grid">
        <div class="field">
          <label>Type</label>
          <div
            id="entry-type-toggle"
            class="dialog-type-toggle"
            role="group"
            aria-label="Select transaction type"
            data-testid="expense-entry-type-select"
          >
            <button
              type="button"
              [class.active]="form.controls.entry_type.value === 'expense'"
              (click)="setDialogEntryType('expense')"
              [attr.aria-pressed]="form.controls.entry_type.value === 'expense'"
              data-testid="expense-entry-type-expense"
            >
              Expense
            </button>
            <button
              type="button"
              [class.active]="form.controls.entry_type.value === 'income'"
              (click)="setDialogEntryType('income')"
              [attr.aria-pressed]="form.controls.entry_type.value === 'income'"
              data-testid="expense-entry-type-income"
            >
              Income
            </button>
          </div>
        </div>

        <div class="field">
          <label for="amount">Amount</label>
          <input
            id="amount"
            type="number"
            step="0.01"
            formControlName="amount"
            placeholder="0.00"
            data-testid="expense-amount-input"
          />
        </div>

        <div class="field">
          <label for="currency">Currency</label>
          <select id="currency" formControlName="currency" data-testid="expense-currency-select">
            <option *ngFor="let currency of currencies" [value]="currency.code">{{ currency.label }}</option>
          </select>
        </div>
      </div>

      <div class="field">
        <label for="description">Description</label>
        <input
          id="description"
          type="text"
          formControlName="description"
          placeholder="What did you spend on?"
          data-testid="expense-description-input"
        />
      </div>

      <div class="field">
        <label for="category">Category</label>
        <select
          id="category"
          formControlName="category_id"
          (change)="onCategoryChange()"
          data-testid="expense-category-search-input"
        >
          <option value="" disabled>Select category</option>
          <option *ngFor="let category of formCategories" [value]="category.category_id">
            {{ category.name }}
          </option>
        </select>
      </div>

      <div class="field" *ngIf="selectedCategory?.subcategories?.length">
        <label for="subcategory">Subcategory (Optional)</label>
        <select id="subcategory" formControlName="subcategory_id" data-testid="expense-subcategory-select">
          <option value="">Select subcategory</option>
          <option
            *ngFor="let subcategory of selectedCategory?.subcategories || []"
            [value]="subcategory.subcategory_id"
          >
            {{ subcategory.name }}
          </option>
        </select>
      </div>

      <div class="field">
        <label for="date">Date</label>
        <input id="date" type="date" formControlName="date" data-testid="expense-date-btn" />
      </div>

      <button type="submit" class="btn-primary full" [disabled]="saving" data-testid="expense-submit-btn">
        {{ saving ? 'Saving...' : editingExpense ? 'Update Transaction' : (form.controls.entry_type.value === 'income' ? 'Add Income' : 'Add Expense') }}
      </button>
    </form>
  </div>
</div>

// frontend/src/pages/ExpensesPage.jsx
import { useState, useEffect } from "react";
import Sidebar from "../components/Sidebar";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "../components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "../components/ui/select";
import { Calendar } from "../components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "../components/ui/popover";
import { toast } from "sonner";
import {
  Plus,
  Search,
  Calendar as CalendarIcon,
  Trash2,
  Edit,
  Filter,
} from "lucide-react";
import { format } from "date-fns";

const API_URL = process.env.REACT_APP_BACKEND_URL;

const ExpensesPage = ({ user }) => {
  const [expenses, setExpenses] = useState([]);
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingExpense, setEditingExpense] = useState(null);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterCategory, setFilterCategory] = useState("all");

  const [formData, setFormData] = useState({
    amount: "",
    currency: user?.preferred_currency || "USD",
    description: "",
    category_id: "",
    subcategory_id: "",
    date: new Date(),
  });

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const [expensesRes, categoriesRes] = await Promise.all([
        fetch(`${API_URL}/api/expenses`, { credentials: "include" }),
        fetch(`${API_URL}/api/categories`, { credentials: "include" }),
      ]);

      if (expensesRes.ok) {
        const expensesData = await expensesRes.json();
        setExpenses(expensesData);
      }

      if (categoriesRes.ok) {
        const categoriesData = await categoriesRes.json();
        setCategories(categoriesData);
      }
    } catch (error) {
      console.error("Error fetching data:", error);
      toast.error("Failed to load expenses");
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    const payload = {
      ...formData,
      amount: parseFloat(formData.amount),
      date: formData.date.toISOString(),
      subcategory_id: formData.subcategory_id || null,
    };

    try {
      const url = editingExpense
        ? `${API_URL}/api/expenses/${editingExpense.expense_id}`
        : `${API_URL}/api/expenses`;

      const response = await fetch(url, {
        method: editingExpense ? "PUT" : "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(payload),
      });

      if (!response.ok) throw new Error("Failed to save expense");

      toast.success(editingExpense ? "Expense updated!" : "Expense added!");
      setDialogOpen(false);
      resetForm();
      fetchData();
    } catch (error) {
      toast.error(error.message);
    }
  };

  const handleDelete = async (expenseId) => {
    if (!window.confirm("Are you sure you want to delete this expense?")) return;

    try {
      const response = await fetch(`${API_URL}/api/expenses/${expenseId}`, {
        method: "DELETE",
        credentials: "include",
      });

      if (!response.ok) throw new Error("Failed to delete expense");

      toast.success("Expense deleted!");
      fetchData();
    } catch (error) {
      toast.error(error.message);
    }
  };

  const handleEdit = (expense) => {
    setEditingExpense(expense);
    setFormData({
      amount: expense.amount.toString(),
      currency: expense.currency,
      description: expense.description,
      category_id: expense.category_id,
      subcategory_id: expense.subcategory_id || "",
      date: new Date(expense.date),
    });
    setDialogOpen(true);
  };

  const resetForm = () => {
    setEditingExpense(null);
    setFormData({
      amount: "",
      currency: user?.preferred_currency || "USD",
      description: "",
      category_id: "",
      subcategory_id: "",
      date: new Date(),
    });
  };

  const getCategory = (categoryId) =>
    categories.find((c) => c.category_id === categoryId);

  const getSubcategory = (categoryId, subcategoryId) => {
    const cat = getCategory(categoryId);
    return cat?.subcategories?.find((s) => s.subcategory_id === subcategoryId);
  };

  const selectedCategory = getCategory(formData.category_id);

  const filteredExpenses = expenses.filter((exp) => {
    const matchesSearch = exp.description
      .toLowerCase()
      .includes(searchTerm.toLowerCase());
    const matchesCategory =
      filterCategory === "all" || exp.category_id === filterCategory;
    return matchesSearch && matchesCategory;
  });

  const formatCurrency = (amount, currency) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: currency || "USD",
    }).format(amount);
  };

  return (
    <div className="min-h-screen bg-[#F8F9FA]" data-testid="expenses-page">
      <Sidebar user={user} />

      <main className="lg:ml-64 p-6 lg:p-8">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
          <div>
            <h1 className="text-3xl font-black tracking-tight">Expenses</h1>
            <p className="text-muted-foreground">
              Track and manage your spending
            </p>
          </div>

          <Dialog
            open={dialogOpen}
            onOpenChange={(open) => {
              setDialogOpen(open);
              if (!open) resetForm();
            }}
          >
            <DialogTrigger asChild>
              <Button
                className="bg-[#064E3B] hover:bg-[#064E3B]/90 rounded-full px-6"
                data-testid="add-expense-dialog-btn"
              >
                <Plus className="w-4 h-4 mr-2" />
                Add Expense
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-md">
              <DialogHeader>
                <DialogTitle>
                  {editingExpense ? "Edit Expense" : "Add New Expense"}
                </DialogTitle>
              </DialogHeader>
              <form onSubmit={handleSubmit} className="space-y-4 mt-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <Label htmlFor="amount">Amount</Label>
                    <Input
                      id="amount"
                      type="number"
                      step="0.01"
                      placeholder="0.00"
                      value={formData.amount}
                      onChange={(e) =>
                        setFormData({ ...formData, amount: e.target.value })
                      }
                      className="mt-1"
                      required
                      data-testid="expense-amount-input"
                    />
                  </div>
                  <div>
                    <Label>Currency</Label>
                    <Select
                      value={formData.currency}
                      onValueChange={(value) =>
                        setFormData({ ...formData, currency: value })
                      }
                    >
                      <SelectTrigger className="mt-1" data-testid="expense-currency-select">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="USD">USD ($)</SelectItem>
                        <SelectItem value="EUR">EUR (€)</SelectItem>
                        <SelectItem value="GBP">GBP (£)</SelectItem>
                        <SelectItem value="INR">INR (₹)</SelectItem>
                        <SelectItem value="JPY">JPY (¥)</SelectItem>
                        <SelectItem value="CAD">CAD (C$)</SelectItem>
                        <SelectItem value="AUD">AUD (A$)</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div>
                  <Label htmlFor="description">Description</Label>
                  <Input
                    id="description"
                    placeholder="What did you spend on?"
                    value={formData.description}
                    onChange={(e) =>
                      setFormData({ ...formData, description: e.target.value })
                    }
                    className="mt-1"
                    required
                    data-testid="expense-description-input"
                  />
                </div>

                <div>
                  <Label>Category</Label>
                  <Select
                    value={formData.category_id}
                    onValueChange={(value) =>
                      setFormData({
                        ...formData,
                        category_id: value,
                        subcategory_id: "",
                      })
                    }
                  >
                    <SelectTrigger className="mt-1" data-testid="expense-category-select">
                      <SelectValue placeholder="Select category" />
                    </SelectTrigger>
                    <SelectContent>
                      {categories.map((cat) => (
                        <SelectItem key={cat.category_id} value={cat.category_id}>
                          {cat.name}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {selectedCategory?.subcategories?.length > 0 && (
                  <div>
                    <Label>Subcategory (Optional)</Label>
                    <Select
                      value={formData.subcategory_id}
                      onValueChange={(value) =>
                        setFormData({ ...formData, subcategory_id: value })
                      }
                    >
                      <SelectTrigger className="mt-1" data-testid="expense-subcategory-select">
                        <SelectValue placeholder="Select subcategory" />
                      </SelectTrigger>
                      <SelectContent>
                        {selectedCategory.subcategories.map((sub) => (
                          <SelectItem
                            key={sub.subcategory_id}
                            value={sub.subcategory_id}
                          >
                            {sub.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                )}

                <div>
                  <Label>Date</Label>
                  <Popover>
                    <PopoverTrigger asChild>
                      <Button
                        variant="outline"
                        className="w-full mt-1 justify-start text-left font-normal"
                        data-testid="expense-date-btn"
                      >
                        <CalendarIcon className="mr-2 h-4 w-4" />
                        {format(formData.date, "PPP")}
                      </Button>
                    </PopoverTrigger>
                    <PopoverContent className="w-auto p-0" align="start">
                      <Calendar
                        mode="single"
                        selected={formData.date}
                        onSelect={(date) =>
                          date && setFormData({ ...formData, date })
                        }
                        initialFocus
                      />
                    </PopoverContent>
                  </Popover>
                </div>

                <Button
                  type="submit"
                  className="w-full bg-[#064E3B] hover:bg-[#064E3B]/90"
                  data-testid="expense-submit-btn"
                >
                  {editingExpense ? "Update Expense" : "Add Expense"}
                </Button>
              </form>
            </DialogContent>
          </Dialog>
        </div>

        {/* Filters */}
        <div className="flex flex-col sm:flex-row gap-4 mb-6">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <Input
              placeholder="Search expenses..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10"
              data-testid="expense-search-input"
            />
          </div>
          <Select value={filterCategory} onValueChange={setFilterCategory}>
            <SelectTrigger className="w-full sm:w-48" data-testid="expense-filter-select">
              <Filter className="w-4 h-4 mr-2" />
              <SelectValue placeholder="All Categories" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Categories</SelectItem>
              {categories.map((cat) => (
                <SelectItem key={cat.category_id} value={cat.category_id}>
                  {cat.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Expenses List */}
        <Card className="rounded-xl border border-[#E5E7EB] bg-white">
          <CardContent className="p-0">
            {loading ? (
              <div className="p-8 text-center text-muted-foreground">
                Loading expenses...
              </div>
            ) : filteredExpenses.length === 0 ? (
              <div className="p-8 text-center text-muted-foreground">
                No expenses found. Add your first expense!
              </div>
            ) : (
              <div className="divide-y divide-[#E5E7EB]">
                {filteredExpenses.map((expense) => {
                  const category = getCategory(expense.category_id);
                  const subcategory = getSubcategory(
                    expense.category_id,
                    expense.subcategory_id
                  );
                  return (
                    <div
                      key={expense.expense_id}
                      className="p-4 sm:p-6 flex items-center justify-between hover:bg-[#F9FAFB] transition-colors"
                      data-testid={`expense-item-${expense.expense_id}`}
                    >
                      <div className="flex items-center gap-4 flex-1 min-w-0">
                        <div
                          className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
                          style={{ backgroundColor: category?.color || "#064E3B" }}
                        >
                          <span className="text-white text-sm font-bold">
                            {category?.name?.charAt(0) || "E"}
                          </span>
                        </div>
                        <div className="min-w-0 flex-1">
                          <p className="font-medium truncate">
                            {expense.description}
                          </p>
                          <p className="text-sm text-muted-foreground">
                            {category?.name}
                            {subcategory && ` › ${subcategory.name}`}
                          </p>
                        </div>
                      </div>

                      <div className="flex items-center gap-4">
                        <div className="text-right">
                          <p className="font-bold font-mono">
                            {formatCurrency(expense.amount, expense.currency)}
                          </p>
                          <p className="text-xs text-muted-foreground">
                            {format(new Date(expense.date), "MMM d, yyyy")}
                          </p>
                        </div>
                        <div className="flex gap-1">
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 text-muted-foreground hover:text-[#064E3B]"
                            onClick={() => handleEdit(expense)}
                            data-testid={`edit-expense-${expense.expense_id}`}
                          >
                            <Edit className="w-4 h-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-8 w-8 text-muted-foreground hover:text-destructive"
                            onClick={() => handleDelete(expense.expense_id)}
                            data-testid={`delete-expense-${expense.expense_id}`}
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </CardContent>
        </Card>
      </main>
    </div>
  );
};

export default ExpensesPage;
