// expenseTrack_ui/src/app/libs/feature/login-page/login-page.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { AuthService } from '../../data-access/auth/auth.service';
import { Router } from '@angular/router';

@Component({
  selector: 'login-page',
  standalone: false,
  templateUrl: './login-page.component.html',
  styleUrl: './login-page.component.scss',
})
export class LoginPageComponent {
  private auth = inject(AuthService);
  private router = inject(Router);
  form = inject(FormBuilder).nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', Validators.required],
  });
  loading = false;
  error = '';

  onSubmit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.loading = true;
    this.error = '';

    const { email, password } = this.form.getRawValue();
    this.auth.login(email, password).subscribe({
      next: () => {
        this.router.navigate(['/dashboard']);
      },
      error: (err) => {
        this.error = err?.error?.detail || err?.error?.message || 'Login failed';
        this.loading = false;
      },
      complete: () => (this.loading = false)
    });
  }
}




<div class="auth-page" data-testid="login-page">
  <div class="auth-form-column">
    <a routerLink="/" class="brand">
      <span class="brand-logo">ET</span>
      <span class="brand-text">ExpenseTrack</span>
    </a>

    <div class="panel">
      <h1>Welcome Back</h1>
      <p class="subtext">Sign in to continue managing your expenses</p>

      <form [formGroup]="form" (ngSubmit)="onSubmit()" novalidate>
        <div class="field">
          <label for="email">Email</label>
          <input
            id="email"
            type="email"
            formControlName="email"
            placeholder="you@example.com"
            data-testid="email-input"
          />
          <small *ngIf="form.controls.email.invalid && form.controls.email.touched">
            Valid email is required.
          </small>
        </div>

        <div class="field">
          <label for="password">Password</label>
          <input
            id="password"
            type="password"
            formControlName="password"
            placeholder="Enter your password"
            data-testid="password-input"
          />
          <small *ngIf="form.controls.password.invalid && form.controls.password.touched">
            Password is required.
          </small>
        </div>

        <button
          type="submit"
          class="submit-btn"
          [disabled]="loading"
          data-testid="login-submit-btn"
        >
          {{ loading ? 'Signing in...' : 'Sign In' }}
        </button>
      </form>

      <p class="info" *ngIf="infoMessage">{{ infoMessage }}</p>

      <p class="switch-link">
        Don't have an account?
        <a routerLink="/register" data-testid="register-link">Create one</a>
      </p>

      <p class="error" *ngIf="error">{{ error }}</p>
    </div>
  </div>

  <div class="auth-visual-column">
    <img
      src="https://images.unsplash.com/photo-1769069920214-732c93825209?crop=entropy&cs=srgb&fm=jpg&q=85&w=800"
      alt="Finance background"
    />
    <div class="overlay">
      <h2>Track Every Penny</h2>
      <p>Get detailed spending insights and make better financial decisions.</p>
    </div>
  </div>
</div>

// frontend/src/pages/LoginPage.jsx
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { Label } from "../components/ui/label";
import { toast } from "sonner";
import { Wallet, Mail, Lock, ArrowRight } from "lucide-react";

const API_URL = process.env.REACT_APP_BACKEND_URL;

const LoginPage = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      const response = await fetch(`${API_URL}/api/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify(formData),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.detail || "Login failed");
      }

      toast.success("Welcome back!");
      navigate("/dashboard");
    } catch (error) {
      toast.error(error.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex" data-testid="login-page">
      {/* Left Side - Form */}
      <div className="w-full lg:w-1/2 flex flex-col justify-center px-8 md:px-16 lg:px-24 py-12">
        <Link to="/" className="flex items-center gap-2 mb-12">
          <div className="w-8 h-8 bg-[#064E3B] rounded-lg flex items-center justify-center">
            <Wallet className="w-5 h-5 text-white" />
          </div>
          <span className="font-bold text-xl tracking-tight">ExpenseTrack</span>
        </Link>

        <div className="max-w-sm">
          <h1 className="text-3xl md:text-4xl font-black tracking-tight mb-2">
            Welcome Back
          </h1>
          <p className="text-muted-foreground mb-8">
            Sign in to continue managing your expenses
          </p>

          {/* <div className="relative mb-6">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-[#E5E7EB]"></div>
            </div>
            <div className="relative flex justify-center text-xs uppercase">
              <span className="bg-white px-4 text-muted-foreground">
                or continue with email
              </span>
            </div>
          </div> */}

          {/* Email Login Form */}
          <form onSubmit={handleSubmit} className="space-y-4">
            <div>
              <Label htmlFor="email" className="text-sm font-medium">
                Email
              </Label>
              <div className="relative mt-1">
                <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                <Input
                  id="email"
                  name="email"
                  type="email"
                  placeholder="you@example.com"
                  value={formData.email}
                  onChange={handleChange}
                  className="pl-10 h-12 rounded-lg border-2 border-[#E5E7EB] bg-[#F9FAFB] focus:border-[#064E3B]"
                  required
                  data-testid="email-input"
                />
              </div>
            </div>

            <div>
              <Label htmlFor="password" className="text-sm font-medium">
                Password
              </Label>
              <div className="relative mt-1">
                <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                <Input
                  id="password"
                  name="password"
                  type="password"
                  placeholder="••••••••"
                  value={formData.password}
                  onChange={handleChange}
                  className="pl-10 h-12 rounded-lg border-2 border-[#E5E7EB] bg-[#F9FAFB] focus:border-[#064E3B]"
                  required
                  data-testid="password-input"
                />
              </div>
            </div>

            <Button
              type="submit"
              size="lg"
              className="w-full bg-[#064E3B] hover:bg-[#064E3B]/90 rounded-lg h-12 text-base font-bold"
              disabled={loading}
              data-testid="login-submit-btn"
            >
              {loading ? (
                <span className="flex items-center">
                  <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin mr-2"></div>
                  Signing in...
                </span>
              ) : (
                <span className="flex items-center">
                  Sign In <ArrowRight className="ml-2 w-5 h-5" />
                </span>
              )}
            </Button>
          </form>

          <p className="text-center text-muted-foreground mt-6">
            Don't have an account?{" "}
            <Link
              to="/register"
              className="text-[#064E3B] font-semibold hover:underline"
              data-testid="register-link"
            >
              Create one
            </Link>
          </p>
        </div>
      </div>

      {/* Right Side - Image */}
      <div className="hidden lg:block w-1/2 bg-[#064E3B] relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#064E3B] to-[#064E3B]/80"></div>
        <img
          src="https://images.unsplash.com/photo-1769069920214-732c93825209?crop=entropy&cs=srgb&fm=jpg&q=85&w=800"
          alt="Finance"
          className="absolute inset-0 w-full h-full object-cover mix-blend-overlay opacity-30"
        />
        <div className="absolute inset-0 flex items-center justify-center p-12">
          <div className="text-center text-white">
            <h2 className="text-4xl font-black tracking-tight mb-4">
              Track Every Penny
            </h2>
            <p className="text-white/80 text-lg max-w-md">
              Get detailed insights into your spending habits and make smarter
              financial decisions.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LoginPage;
